#!/bin/sh
# Regenerate T80s_ghdl.v: the FPGA's Z80 (rtl/audio/T80, VHDL) converted to
# Verilog with GHDL's synthesizer so the board bench runs the same core the
# DE10 runs. tv80 (verif/board/tv80) stayed as the fast alternative
# (make ... Z80=tv80), but it is not the hardware's Z80: the sound crashes
# of M6 lived on the T80s side and tv80 never showed them.
# Needs GHDL 6 (the Homebrew cask is disabled on macOS 26; the GitHub
# release ghdl-llvm-6.0.0-macos15-aarch64 runs fine from any directory).
# One source patch: T80.vhd:644 "ioq and x\"7\"" mixes a 9-bit and a 4-bit
# vector, which Quartus tolerates and GHDL refuses; the 9-bit literal below
# is the meaning (keep the low three bits).
set -e
GHDL=${GHDL:-ghdl}
HERE=$(cd "$(dirname "$0")" && pwd)
SRC=$HERE/../../../rtl/audio/T80
W=$(mktemp -d)
cp $SRC/T80.vhd $SRC/T80_ALU.vhd $SRC/T80_MCode.vhd $SRC/T80_Reg.vhd $SRC/T80s.vhd $W/
sed -i '' 's/ioq := (ioq and x"7") xor/ioq := (ioq and "000000111") xor/' $W/T80.vhd
cd $W
$GHDL -i --std=08 -fsynopsys T80.vhd T80_ALU.vhd T80_MCode.vhd T80_Reg.vhd T80s.vhd
$GHDL -m --std=08 -fsynopsys T80s
{ echo "// GENERATED by verif/board/t80/gen.sh from rtl/audio/T80 (GHDL $($GHDL --version | head -1 | cut -d' ' -f2)); do not edit";
  $GHDL --synth --std=08 -fsynopsys --out=verilog T80s; } > $HERE/T80s_ghdl.v
rm -rf $W
echo "wrote $HERE/T80s_ghdl.v ($(wc -l < $HERE/T80s_ghdl.v) lines)"
